### ISSUE TITLE
Modified XmlElementRef content can only partially rendered in yjs

### ISSUE THREAD

**Issue by stellit** [y-crdt/y-crdt#303] opened 2023-06-27 11:16 UTC
When modify the XmlElementRef in yrs, the serialized update can be read properly, but the content is partially missing. 

Here is the sample code that produce the update:
```rust
#[test]
fn test_xml_attr_alter() {
    let update = "AAEAC9ynrqMOBLudpN4NBAAEAQEACycABAAHACgDCAAomgGGAW5vdGUudGl0bGV0aXRsZTFwcm9zZW1pcnJvcmxpbmtub3RlZ3VpZHNsb3RHdWlkdHlwZWxpbmtUeXBlYm5vdGUuZ3VpZG5vdGVHdWlkbm90ZS5vd25lcm93bmVybm90ZS50eXBlbm90ZVR5cGVub3RlLmNyZWF0ZVRpbWVjcmVhdGVUaW1lCgUBCwgECAQIAQkICgUJCA8KCQEAAAABAAADAQICAwJBBwIIAHcWVG9sTnU2VHFUMmUwb0FmNXQ1eVlyQXcWRktBR2xydFNTaVNLaUVQRlRJZGwzQXcIbGlua25vdGV3ATF3FlRvbE51NlRxVDJlMG9BZjV0NXlZckEEAHcWdXlaaHl4V0hTa3VtdGpLbkItejJld30ifQB3DTE2ODc4NjAxNzE4ODEA";
    // "AAEAG6_ctakS3Keuow4Au52k3g3cp66jDgS7naTeDQcGCE4ABAEBABGkAIgAqAAnAAQABwAoAwgAKLEBnAEwdW9aRUNaM1JZU3NRRjVhU2xPWUNBbm90ZS50aXRsZXRpdGxlMXByb3NlbWlycm9ybGlua25vdGVndWlkc2xvdEd1aWR0eXBlbGlua1R5cGVibm90ZS5ndWlkbm90ZUd1aWRub3RlLm93bmVyb3duZXJub3RlLnR5cGVub3RlVHlwZW5vdGUuY3JlYXRlVGltZWNyZWF0ZVRpbWUWCgUBCwgECAQIAQkICgUJCA8KCQEAAAABAAADAQICAwJBCQMDAHcWMHVvWkVDWjNSWVNzUUY1YVNsT1lDQXcWQkNYMGY4R1NRQ2V4c1hOemI5dUlMQQgAdxZUb2xOdTZUcVQyZTBvQWY1dDV5WXJBdxZGS0FHbHJ0U1NpU0tpRVBGVElkbDNBdwhsaW5rbm90ZXcBMXcWVG9sTnU2VHFUMmUwb0FmNXQ1eVlyQQQAdxZ1eVpoeXhXSFNrdW10aktuQi16MmV3fSJ9AHcNMTY4Nzg2MDE3MTg4MQLck9eRBwIDAAMA-46S7wYBAAA"];
    let doc = Doc::with_options(Options {
        skip_gc: true,
        ..Default::default()
    });
    {
        let mut txn = doc.transact_mut();
        txn.apply_update(Update::decode_v2(&decode_base64_url_safe(update).unwrap()).unwrap());
    }
    let linked_notes = walk_through_for_sub_block_seq(&doc);

    {
        let mut txn = doc.transact_mut();
        for linked_note in linked_notes.iter() {
            linked_note
                .elem_ref
                .insert_attribute(&mut txn, "guid", "AAEAG6_ctakS3Keuow4Au5");
        }
    }
    let txn = doc.transact();
    let bin = txn.encode_state_as_update_v2(&StateVector::default());
    let output = encode_base64_url_safe(&bin);
    println!("{}", output);
}

pub fn walk_through_for_sub_block_seq(note_doc: &Doc) -> Vec<BlockLink> {
    let mut blocks = vec![];
    let fragment = note_doc.get_or_insert_xml_fragment("prosemirror");
    let txn = note_doc.transact();
    let walker = fragment.successors(&txn);
    for ref mut node in walker {
        if let yrs::XmlNode::Element(element) = node {
            let tag = element.tag().as_ref();
            if tag.eq("linknote") {
                let child_guid = element.get_attribute(&txn, "guid");
                if child_guid.is_none() {
                    continue;
                }
                blocks.push(BlockLink {
                    child: child_guid.unwrap(),
                    elem_ref: element.clone(),
                });
            }
        }
    }
    blocks
}

pub struct BlockLink {
    pub child: String,
    pub elem_ref: XmlElementRef,
}```

the guid is set to `AAEAG6_ctakS3Keuow4Au5`, but at yjs only last char `5` is preserved.

here is the sample code that to serialize at yjs code:
```typescript
test('test malform', () => {
    const doc = new Y.Doc({
        true,
        gcFilter: () => {
            return true;
        }
    });
    const update = "AAEAFdynrqMOBLudpN4NpJL9qAucp66jDgUABAEBAgANJwAEAAcAKAMIACgDpLEBnAFub3RlLnRpdGxldGl0bGUxcHJvc2VtaXJyb3JsaW5rbm90ZWd1aWRzbG90R3VpZHR5cGVsaW5rVHlwZWJub3RlLmd1aWRub3RlR3VpZG5vdGUub3duZXJvd25lcm5vdGUudHlwZW5vdGVUeXBlbm90ZS5jcmVhdGVUaW1lY3JlYXRlVGltZUFBRUFHNl9jdGFrUzNLZXVvdzRBdTUKBQELCAQIBAgBCQgKBQkIDwoWCQEAAAABAAADAQICAwJBBwMIAHcWVG9sTnU2VHFUMmUwb0FmNXQ1eVlyQXcWRktBR2xydFNTaVNLaUVQRlRJZGwzQXcIbGlua25vdGV3ATF3FlRvbE51NlRxVDJlMG9BZjV0NXlZckEEAHcWdXlaaHl4V0hTa3VtdGpLbkItejJld30ifQB3DTE2ODc4NjAxNzE4ODEBAAHck9eRBwEDAA";

    Y.applyUpdateV2(doc, Buffer.from(update, 'base64url'));
    console.debug(`doc after update ${doc.getXmlFragment('prosemirror')}`);

});
```

**Comment by Horusiath** [comment] 2023-06-27 18:22
@stellit I think, I've managed to track an issue.

The cause of the bug is that in Yrs inserted attributes are marked as a Text content (same as chunks of data used in YText type), while in Yjs they are threated as as Any content (same as individual elements of arrays). This changes an interpretation a little as Text content is splittable, while Any isn't. Now map type that's underpinning the attributes, keeps them basically as collection of chunks of values and tries to read the most recent value. Since Text is splittable, "the most recent" means the last character.

This isn't an issue between two Yrs instances, as in map-like types, Text content is read as a single entity, but once it's passed down to Yjs, it causes a problem.

I'll release the fix soon.

**Closed** 2023-06-27 18:43 UTC
Labels: bug

**Comment by stellit** [comment] 2023-06-28 06:30
Hi Bartosz,

that's really a rush fix! Thanks a lot! Furthermore, thanks for explain the details how attribute is handled in yjs/yrs~
