### ISSUE TITLE
Compatibility issue to yjs while integrate item with no parent

### ISSUE THREAD

**Issue by stellit** [y-crdt/y-crdt#181] opened 2022-08-30 01:32 UTC
I've noticed that there is a slight difference between the yjs and yrs during the block integrate() when no parent is found for the current Item:
yjs: recognize the item as GC item and continue the integration:
https://github.com/yjs/yjs/blob/main/src/structs/Item.js#L525
yrs: raise the case as a panic:
https://github.com/y-crdt/y-crdt/blob/main/yrs/src/block.rs#L422

here is a test doc produced by yjs:
[origin.base64url.txt](https://github.com/y-crdt/y-crdt/files/9448828/origin.base64url.txt)

I've try to tread it as GC item in yrs but no luck.

**Comment by Horusiath** [comment] 2022-09-02 04:51
Thanks for reporting this issue. I'll take a look at it.

**Comment by Horusiath** [comment] 2022-09-19 13:44
For some reason I don't get yet, this PR causes macOS tests to go wild on invalid memory references. I've initially thought that it may be caused by some internal cross-build caching in Github Actions, but once I've recreated the PR in #192 the issue still appears.

**Comment by Horusiath** [comment] 2022-11-23 16:11
I didn't provide an update on this issue straight after fixing it, but this should be fixed somewhere around v0.12.2-v0.13.

**Closed by Horusiath** 2022-11-23 16:11 UTC
Labels: bug
